/**
 * `@fingate/shared/ui` — re-export cho Design System (§12.5 giữ nguyên tên gọi).
 *
 * Đây chỉ là lớp re-export: `status/registry` + `money` là nguồn sự thật và dùng được
 * ở cả hai phía (ADR-09). Component `Fg*` nằm ở `apps/web/src/components/` — API không
 * bao giờ import file này (lint chặn hướng import, architecture §4).
 */

export {
  // registry & tone
  type Tone,
  TONES,
  type StatusKey,
  STATUS_REGISTRY,
  STATUS_KEYS,
  PENDING_STATUSES,
  TERMINAL_STATUSES,
  isStatusKey,
  statusLabel,
  statusTone,
  statusOwnerRole,
  statusChipLabel,
  pendingStatusForRole,
  type AccountStatusKey,
  ACCOUNT_STATUS_REGISTRY,
  accountStatusFor,
  type SeverityLevel,
  type MaturityBand,
  maturity,
  maturityLabel,
  daysLabel,
  MATURITY_BUCKETS,
  type MaturityBucket,
  type Role,
  ROLES,
  APPROVAL_ORDER,
  type DocKind,
  DOC_KINDS,
  DOC_KIND_LABEL,
  DOC_CODE_PREFIX,
  type EvidenceType,
  EVIDENCE_TYPES,
  EVIDENCE_LABEL,
  type Action,
  ACTIONS,
  ACTION_LABEL,
  ACTION_REQUIRES_OPINION,
} from '../status/index.js';

export {
  type Currency,
  CURRENCIES,
  CURRENCY_CODES,
  currencyDecimals,
  asCurrency,
  type Money,
  money,
  ZERO,
  toMinor,
  moneyToWire,
  moneyFromWire,
  add,
  sub,
  neg,
  abs,
  sum,
  sumMinor,
  cmp,
  gte,
  lt,
  isZero,
  isNegative,
  isPositive,
  isMoney,
  divRound,
  convert,
  percentOf,
  ratioOf,
  type MoneyMode,
  type FormatMoneyOptions,
  formatMoney,
  formatMoneyOrMissing,
  moneyAria,
  moneyInputValue,
  parseMoneyInput,
  MINUS,
  MISSING,
  num,
  pct,
  rateLabel,
  countUnit,
  VN_TZ,
  vnDate,
  vnTime,
  vnWeekday,
  ddmmyyyy,
  shortDate,
  dateTimeLabel,
  weekdayDate,
  daysBetween,
  daysUntil,
  addDays,
  monthRange,
  today,
  now,
  relativeTime,
  isBusinessDate,
  numberFormatter,
} from '../money/index.js';

/** Tiện gọn cho screen: `fmt.money(...)` khớp cách gọi trong Design System §4.2. */
import * as moneyNs from '../money/index.js';
export const fmt = moneyNs;
